### ISSUE TITLE
clean up explorer_db when restart explorer node

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/experiment-deploy#261]
As requested by @rlan35 , we need to clean up explorer_db whenever we restart the explorer node process.  This can be incorporated into the restart_node.sh script to clean up the explorer db.  

@rlan35 , just want to double check with you that every time the explorer node process was restarted, we need to clean the db due to the known bug.

**Comment by LeoHChen** [comment]
This is a work around of https://github.com/harmony-one/harmony/issues/2831

After that bug is fixed and deployed, we don't have to do the clean up.

**Comment by AndyBoWu** [comment]
PR: https://github.com/harmony-one/experiment-deploy/pull/262/files

**Comment by LeoHChen** [comment]
need improvement

**Comment by LeoHChen** [comment]
no longer needed, per @denniswon
