### ISSUE TITLE
Migrate Explorer To newer instance running Amazon Linux 2

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/experiment-deploy#266]
Need to build new instance for explorer, the new instance needs to run on Amazon Linux 2 which has systemd support. The existing explorer runs on Amazon Linux AMI which has no systemd support makes the automation much harder.

**Comment by janet-harmony** [comment]
1. Created 2 new instances in each region.
2. Used rclone to get the archival shard db & state pruned beacon db.
3. Let the machines sync to latest chain.
4. Swapped the elastic IP to the new machines.
5. Restarted block explorer backend.
6. Updated the target groups for the load balancers.
7. Stopped one of the old machines & keep the other for internal explorer use.
