### ISSUE TITLE
Support Azure nodes for mainnet

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/experiment-deploy#282]
Our current mainnet support both AWS and GCP nodes.  We have credit from Azure, so we shall consider adding Azure support.

The current process is to launch node using terraform (both aws/gcp), and use systemd managed harmony service to join the network. We have separate scripts in experiment-deploy/tf/aws.1 and experiment-deploy/tf/gcp to handle the new node, using `newmk` option.

Please add a similar support for Azure.  We shall use the same key, and firewall settings.

**Comment by LeoHChen** [comment]
Noted, nodedb has to support azure as well.

**Comment by LeoHChen** [comment]
@jhd2best , how is the nodedb support?

**Comment by jhd2best** [comment]
already let nodedb support Azure. see https://github.com/harmony-one/nodedb/pull/27
