### ISSUE TITLE
[ansible] support regular validator node and explorer node

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/experiment-deploy#293]
regular validator node and explorer node are using different systemd service file, and different key setup.

regular validator nodes have multiple blskeys in .hmy/blskeys directory
explorer nodes just have a dummy key in .hmy/blskeys directory.

The node role should be able to differentiate regular nodes and explorer nodes using conditions of ansible.

**Comment by jhd2best** [comment]
PR:https://github.com/harmony-one/experiment-deploy/pull/299
