### ISSUE TITLE
[ansible] support customized network in node role

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/experiment-deploy#311]
Our current node role in ansible is hardcoded to support only OSTN, like -N staking in systemd service.

We should support a flexible configuration of where to download node binary and node.sh, so that we can provision testnet node.  We can use some default var, and use configuration to support other networks.

**Comment by LeoHChen** [comment]
other networks like STN, or DRYRUN network.

**Comment by jhd2best** [comment]
PR:https://github.com/harmony-one/experiment-deploy/pull/323
but maybe need modify after start Open Staking on mainnet
