### ISSUE TITLE
[mainnet] migrate legacy nodes to run systemd service

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/experiment-deploy#312]
To prepare for the upcoming mainnet upgrade of open staking, we'd better convert all nodes to use the systemd service.  I am aware of a few nodes are still using the legacy way "nohup" to run harmony node, please convert them all to use the systemd service to run the node.

I've added a script to do the conversion.
https://github.com/harmony-one/experiment-deploy/blob/master/tools/enable-systemd-service.sh

To check if the node is running systemd, you may use the `systemctl status harmony` to check.

Please track the progress in this issue.

**Comment by Daniel-VDM** [comment]
Used the following command to check for machines that need to be upgraded:
```bash
./run_on_shard.sh -y -p s3 -T 3 'systemctl | grep harmony || echo "FAIL: $(hostname --ip-address)"' > s3_systemctl_scan.txt
```

Got the following:

## s3 machines to upgrade:
```
172.31.38.230
172.31.0.171
```

## s2 machines to upgrade:
```
172.31.6.135
172.31.5.248
172.31.1.140
172.31.6.15
172.31.24.204
```

All other shards are fully upgraded already.

**Comment by Daniel-VDM** [comment]
All machines upgraded
