### ISSUE TITLE
[lrtn] re-launch a new long running test net

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/experiment-deploy#327]
We can terminate the current LRTN and launch a new one. The current one is no longer updated and is outdated.

**Comment by LeoHChen** [comment]
@Daniel-VDM , can you add a few info about the new LRTN you launched here?  And close this ticket. THanks.

**Comment by Daniel-VDM** [comment]
Endpoints:
```
https://api.s0.b.hmny.io/
https://api.s1.b.hmny.io/
https://api.s2.b.hmny.io/
https://api.s3.b.hmny.io/
```

Watchdog:
http://watchdog.hmny.io/report-testnet

Network (for node.sh) `-n testnet`.

**Comment by Daniel-VDM** [comment]
Config for binary is [here](https://github.com/harmony-one/harmony/blob/master/internal/configs/sharding/testnet.go)

Config for deploy:
* [benchmark file](https://github.com/harmony-one/experiment-deploy/blob/master/configs/benchmark-lrtn.json)
* [launch file](https://github.com/harmony-one/experiment-deploy/blob/master/configs/launch-lrtn.json)
* [explorer userdata](https://github.com/harmony-one/experiment-deploy/blob/master/configs/userdata-systemd-static-lrtn-exp.sh)
* [node userdata](https://github.com/harmony-one/experiment-deploy/blob/master/configs/userdata-systemd-static-lrtn.sh)

**Comment by Daniel-VDM** [comment]
Common commands can be found [here](https://gist.github.com/Daniel-VDM/23f60e01813d633bc60119c3d1966333)
