### ISSUE TITLE
Bring the Puzzle Game service Online ASAP

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/experiment-deploy#93]
Priority: HIGH

Repo: https://github.com/harmony-one/demo-apps

**Comment by AndyBoWu** [comment]
Profile used for the Puzzle game: -cello

In this path: /home/ec2-user/go/src/github.com/harmony-one/experiment-deploy/configs

benchmark-cello.json
launch-cello.json

**Comment by AndyBoWu** [comment]
Finished the meeting with LC

* Need to create a new {benchark, launch} profile for the puzzle game
* A few features had been removed such that it wont be easy to restart the blockchain in the backend
* Some of the work was maintained by AK, not able to reach out to him at the moment
* deep dive to the code to see where to find the proper version for this task

**Comment by AndyBoWu** [comment]
Task: create a `-puzzle` profile based on the `-4chards` profile.

**Comment by john-harmony** [comment]
Puzzle deployment notes are being documented [here](https://docs.harmony.one/onboarding-wiki/release-management/puzzle-deploy)

**Comment by AndyBoWu** [comment]
Branch for this app: harmony-one/harmony:cello-branch

**Comment by AndyBoWu** [comment]
Progress: `cello` branch was recreated in the harmony repo, and created a new {benchmark, launch}-puzzle profile.

TO-DO (for today):
* reached out a few engs yesterday, need to invite them again to restart the puzzle game blockchain
* reached out to Minh to enable puzzle game without backend

**Comment by AndyBoWu** [comment]
Puzzle game is online, working on the documentation.

**Comment by AndyBoWu** [comment]
Documentation has been postponed due to [this ticket](https://github.com/harmony-one/harmony-ops/issues/50)
